routes/web.php
<?php

use App\Http\Controllers\BackgroundController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentCourseController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TeacherCourseController;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');
Route::resource('student', StudentController::class);
Route::resource('teacher', TeacherController::class);
Route::resource('course', CourseController::class);
Route::resource('background', BackgroundController::class);
Route::resource('studentCourse', StudentCourseController::class);
Route::resource('teacherCourse', TeacherCourseController::class);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravolt\Support\Traits\AutoSearch;
use Laravolt\Support\Traits\AutoSort;

class Student extends Model
{
    use HasFactory;
    use AutoSearch;
    use AutoSort;

    protected $searchableColumns = ['nama'];
    protected $fillable = ['nama', 'jenis_kelamin', 'tempat_lahir', 'tanggal_lahir'];

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'course_student', 'student_id', 'course_id');
    }
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StudentStoreRequest;
use App\Models\Course;
use App\Models\Student;
use Illuminate\Http\Request;

class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::autoSearch(request('search'))->autoSort()->paginate(5);

        return view('student.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StudentStoreRequest $request)
    {
        Student::create($request->all());

        return redirect('student')->withSuccess('Berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Student $student)
    {
        $courses = Course::whereNotIn('id', $student->courses->pluck('id'))->pluck('nama', 'id');
        $studentCourses = $student->courses;

        return view('student.show', compact('student', 'courses', 'studentCourses'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Student $student)
    {
        return view('student.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(StudentStoreRequest $request, $id)
    {
        Student::find($id)->update($request->all());

        return back()->withSuccess('Berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Student $student)
    {
        $student->delete();

        return back()->withSuccess('Berhasil didelete!');
    }
}

resources/views/student/_form.blade.php
{!! form()->text('nama')->placeholder('Nama Lengkap')->label('Nama') !!}
{!! 
    form()->select('jenis_kelamin')
    ->placeholder('Pilih')
    ->appendOption('L', 'Laki-laki')
    ->appendOption('P', 'Perempuan')
    ->label('Jenis Kelamin');
!!}
{!! form()->text('tempat_lahir')->placeholder('Tempat Lahir')->label('Tempat Lahir') !!}
{!! form()->date('tanggal_lahir')->label('Tanggal Lahir') !!}
{!! form()->submit(); !!}

resources/views/student/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Tambah Student" />

    {!! form()->open(route('student.store')) !!}
        @include('student._form')
    {!! form()->close() !!}

@stop

resources/views/student/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Edit Student" />

    {!! form()->bind($student)->put(route('student.update', $student->id)) !!}
        @include('student._form')
    {!! form()->close() !!}

@stop

resources/views/student/index.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Student">
        <x-item>
            <x-link label="Tambah" icon="plus" url="{{ route('student.create') }}"></x-link>
        </x-item>
    </x-titlebar>

    {!! Suitable::source($students)->search()->columns([
            \Laravolt\Suitable\Columns\Numbering::make('No'),
            \Laravolt\Suitable\Columns\Text::make('nama', 'Nama')->sortable('nama'),
            \Laravolt\Suitable\Columns\RestfulButton::make('student', 'Aksi')
        ])->render() 
    !!}

@stop

resources/views/student/show.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Detail Student" />

    <div class="ui two column doubling stackable grid container">
        <div class="column">
            <div class="ui card">
                <div class="image">
                    <img src="/images/default.png" alt="">
                </div>
                <div class="content">
                    <a class="header">{{ $student->nama }}</a>
                    <div class="meta">
                        <span class="date">Joined in {{ $student->created_at }}</span>
                    </div>
                    <div class="description">
                        Kristy is an art director living in New York.
                    </div>
                </div>
                <div class="extra content">
                    <a>
                        <i class="user icon"></i>
                        22 Friends
                    </a>
                </div>
            </div>
        </div>
        <div class="column">
            {!! Suitable::source($studentCourses)->search()->columns([
                    \Laravolt\Suitable\Columns\Numbering::make('No'),
                    \Laravolt\Suitable\Columns\Text::make('nama', 'Nama')->sortable('nama'),
                    \Laravolt\Suitable\Columns\Text::make('kelas', 'Kelas'),
                    \Laravolt\Suitable\Columns\Text::make('sks', 'Sks'),
                    \Laravolt\Suitable\Columns\RestfulButton::make('course', 'Aksi')->except('view', 'edit')
                ])->render() 
            !!}

            {!! form()->post(route('studentCourse.store')) !!}
                {!! form()->hidden('student_id', $student->id); !!}
                {!! form()->dropdown('course_id', $courses)->placeholder('...')->label('Pilih Mata Kuliah') !!}
                {!! form()->submit(); !!}
            {!! form()->close() !!}
        </div>
    </div>

@stop