routes/web.php
<?php

use App\Http\Controllers\BackgroundController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentCourseController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TeacherCourseController;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');
Route::resource('student', StudentController::class);
Route::resource('teacher', TeacherController::class);
Route::resource('course', CourseController::class);
Route::resource('background', BackgroundController::class);
Route::resource('studentCourse', StudentCourseController::class);
Route::resource('teacherCourse', TeacherCourseController::class);

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravolt\Support\Traits\AutoSearch;
use Laravolt\Support\Traits\AutoSort;

class Teacher extends Model
{
    use HasFactory;
    use AutoSearch;
    use AutoSort;

    protected $searchableColumns = ['nama'];
    protected $fillable = ['nama', 'gelar'];

    public function backgrounds()
    {
        return $this->hasMany(Background::class);
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'course_teacher', 'teacher_id', 'course_id');
    }
}

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\TeacherStoreRequest;
use App\Models\Course;
use App\Models\Teacher;
use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teachers = Teacher::autoSearch(request('search'))->autoSort()->paginate(5);

        return view('teacher.index', compact('teachers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teacher.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TeacherStoreRequest $request)
    {
        Teacher::create($request->all());

        return redirect('teacher')->withSuccess('Berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Teacher $teacher)
    {
        $backgrounds = $teacher->backgrounds;
        $courses = Course::whereNotIn('id', $teacher->courses->pluck('id'))->pluck('nama', 'id');
        $teacherCourses = $teacher->courses;

        return view('teacher.show', compact('teacher', 'courses', 'teacherCourses', 'backgrounds'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Teacher $teacher)
    {
        return view('teacher.edit', compact('teacher'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TeacherStoreRequest $request, $id)
    {
        Teacher::find($id)->update($request->all());

        return back()->withSuccess('Berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Teacher $teacher)
    {
        $teacher->delete();

        return back()->withSuccess('Berhasil didelete!');
    }
}

resources/views/teacher/_form.blade.php
{!! form()->text('nama')->placeholder('Nama Lengkap')->label('Nama') !!}
{!! form()->text('gelar')->label('Gelar') !!}
{!! form()->submit(); !!}

resources/views/teacher/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Tambah Teacher" />

    {!! form()->open(route('teacher.store')) !!}
        @include('teacher._form')
    {!! form()->close() !!}

@stop

resources/views/teacher/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Edit Teacher" />

    {!! form()->bind($teacher)->put(route('teacher.update', $teacher->id)) !!}
        @include('teacher._form')
    {!! form()->close() !!}

@stop

resources/views/teacher/index.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Teacher">
        <x-item>
            <x-link label="Tambah" icon="plus" url="{{ route('teacher.create') }}"></x-link>
        </x-item>
    </x-titlebar>

    {!! Suitable::source($teachers)->search()->columns([
            \Laravolt\Suitable\Columns\Numbering::make('No'),
            \Laravolt\Suitable\Columns\Text::make('nama', 'Nama')->sortable('nama'),
            \Laravolt\Suitable\Columns\RestfulButton::make('teacher', 'Aksi')
        ])->render() 
    !!}

@stop

resources/views/teacher/show.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Detail Teacher" />

    <div class="ui two column doubling stackable grid container">
        <div class="column">
            <div class="ui card">
                <div class="image">
                    <img src="/images/default.png" alt="">
                </div>
                <div class="content">
                    <a class="header">{{ $teacher->nama }}</a>
                    <div class="meta">
                        <span class="date">Joined in {{ $teacher->created_at }}</span>
                    </div>
                    <div class="description">
                        Kristy is an art director living in New York.
                    </div>
                </div>
                <div class="extra content">
                    <a>
                        <i class="user icon"></i>
                        22 Friends
                    </a>
                </div>
            </div>
        </div>
        <div class="column">
            {!! Suitable::source($teacherCourses)->search()->columns([
                    \Laravolt\Suitable\Columns\Numbering::make('No'),
                    \Laravolt\Suitable\Columns\Text::make('nama', 'Nama')->sortable('nama'),
                    \Laravolt\Suitable\Columns\Text::make('kelas', 'Kelas'),
                    \Laravolt\Suitable\Columns\Text::make('sks', 'Sks'),
                    \Laravolt\Suitable\Columns\RestfulButton::make('course', 'Aksi')->except('view', 'edit')
                ])->render() 
            !!}

            {!! form()->post(route('teacherCourse.store')) !!}
                {!! form()->hidden('teacher_id', $teacher->id); !!}
                {!! form()->dropdown('course_id', $courses)->placeholder('...')->label('Pilih Mata Kuliah') !!}
                {!! form()->submit(); !!}
            {!! form()->close() !!}

            {!! Suitable::source($backgrounds)->search()->columns([
                    \Laravolt\Suitable\Columns\Numbering::make('No'),
                    \Laravolt\Suitable\Columns\Text::make('strata', 'Strata')->sortable('nama'),
                    \Laravolt\Suitable\Columns\Text::make('jurusan', 'Jurusan'),
                    \Laravolt\Suitable\Columns\Text::make('sekolah', 'Sekolah'),
                    \Laravolt\Suitable\Columns\Text::make('tahun_mulai', 'Mulai'),
                    \Laravolt\Suitable\Columns\Text::make('tahun_selesai', 'Selesai'),
                    \Laravolt\Suitable\Columns\RestfulButton::make('course', 'Aksi')->except('view', 'edit')
                ])->render()
            !!}

            {!! form()->post(route('background.store')) !!}
                {!! form()->hidden('teacher_id', $teacher->id); !!}
                {!! form()->text('strata')->label('Strata') !!}
                {!! form()->text('jurusan')->label('Jurusan') !!}
                {!! form()->text('sekolah')->label('Sekolah') !!}
                {!! form()->text('tahun_mulai')->label('Tahun Mulai') !!}
                {!! form()->text('tahun_selesai')->label('Tahun Selesai') !!}
                {!! form()->submit(); !!}
            {!! form()->close() !!}
        </div>
    </div>

@stop