routes/web.php
<?php

use App\Http\Controllers\BackgroundController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\Home;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StudentCourseController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TeacherCourseController;

Route::get('/', Home::class)->name('home');
Route::get('/dashboard', Dashboard::class)->name('dashboard')->middleware('auth');
Route::resource('student', StudentController::class);
Route::resource('teacher', TeacherController::class);
Route::resource('course', CourseController::class);
Route::resource('background', BackgroundController::class);
Route::resource('studentCourse', StudentCourseController::class);
Route::resource('teacherCourse', TeacherCourseController::class);

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Laravolt\Support\Traits\AutoSearch;
use Laravolt\Support\Traits\AutoSort;

class Course extends Model
{
    use HasFactory;
    use AutoSearch;
    use AutoSort;

    protected $fillable = ['nama', 'sks', 'kelas'];

    public function students()
    {
        return $this->belongsToMany(Student::class, 'course_student', 'student_id', 'course_id');
    }

    public function teachers()
    {
        return $this->belongsToMany(Teacher::class, 'course_teacher');
    }
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CourseStoreRequest;
use App\Models\Course;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $courses = Course::autoSearch(request('search'))->autoSort()->paginate(5);

        return view('course.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('course.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(courseStoreRequest $request)
    {
        Course::create($request->all());

        return redirect('course')->withSuccess('Berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Course $course)
    {
        return view('course.edit', compact('course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CourseStoreRequest $request, $id)
    {
        Course::find($id)->update($request->all());

        return back()->withSuccess('Berhasil diedit!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Course $course)
    {
        $course->delete();

        return back()->withSuccess('Berhasil didelete!');
    }
}

resources/views/course/_form.blade.php
{!! form()->text('nama')->placeholder('Nama Mata Kuliah')->label('Nama') !!}
{!! form()->text('kelas')->label('Kelas') !!}
{!! form()->text('sks')->label('Sks') !!}
{!! form()->submit(); !!}

resources/views/course/create.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Tambah Course" />

    {!! form()->open(route('course.store')) !!}
        @include('course._form')
    {!! form()->close() !!}

@stop

resources/views/course/edit.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Edit Course" />

    {!! form()->bind($course)->put(route('course.update', $course->id)) !!}
        @include('course._form')
    {!! form()->close() !!}

@stop

resources/views/course/index.blade.php
@extends('laravolt::layouts.app')

@section('content')

    <x-titlebar title="Courses">
        <x-item>
            <x-link label="Tambah" icon="plus" url="{{ route('course.create') }}"></x-link>
        </x-item>
    </x-titlebar>

    {!! Suitable::source($courses)->search()->columns([
            \Laravolt\Suitable\Columns\Numbering::make('No'),
            \Laravolt\Suitable\Columns\Text::make('nama', 'Nama')->sortable('nama'),
            \Laravolt\Suitable\Columns\Text::make('kelas', 'Kelas'),
            \Laravolt\Suitable\Columns\Text::make('sks', 'Sks'),
            \Laravolt\Suitable\Columns\RestfulButton::make('course', 'Aksi')
        ])->render() 
    !!}

@stop